### ISSUE TITLE
Enabled fixed sized versions

### ISSUE THREAD

**Issue by BrianSipple** [svgstore/svgstore#14]
One capability that we would have during the conversion process is -- for an individual SVG -- reusing the converted symbol in memory to create multiple versions of it a different "fixed sizes". 

[`grunt-svgstore` provides this feature](https://github.com/FWeinb/grunt-svgstore/blob/master/README.md#optionsfixedsizeversion-since-040). Essentially, it involves:
- Making a new symbol tag
- calculating the symbol's `viewbox` for a specific size,
- placing the contents of the currently converted symbol (the "standard" version, if you will) directly in the middle of the fixed-size `<symbol>`'s viewport,
- applying a unique ID to the symbol based upon a provided suffix

**Comment by shannonmoeller** [comment]
I typically have my sprited svgs scale in relation to a container and control the size of the container with CSS as needed. Forgive me for my ignorance, but what is the practical use case for multiple copies of a symbol at fixed sizes?

**Comment by BrianSipple** [comment]
True true. I'd imagine this would allow for keeping the viewport and container fixed, but then still create a "padding" around the actual content. 

@FWeinb any insight as to what the motivation for this feature was in `grunt-svgstore`.

**Comment by FWeinb** [comment]
@BrianSipple That feature was contributed in FWeinb/grunt-svgstore#110 I don't have much time to support `grunt-svgstore` anymore, I don't have a project that is using it. I really appreciate the afford you are putting into `svgstore`.

**Comment by shannonmoeller** [comment]
While this doesn't count the use cases in closed-source projects, there doesn't seem to be a great demand for this feature:

https://github.com/search?q=fixedSizeVersion&type=Code&utf8=%E2%9C%93

Closing for now.
