### ISSUE TITLE
Attribute preservation

### ISSUE THREAD

**Issue by BrianSipple** [svgstore/svgstore#4]
Custom attribute preservation — defaulting to id, viewbox, role, and aria-labelledby (the latter two are hugely beneficial for screen reader support).

See: https://github.com/jmarquis/broccoli-svgstore/pull/7

**Comment by shannonmoeller** [comment]
Currently, the `.add()` method expects an `id` as the first attribute. Including `id` in the list of attributes to preserve by default could lead to collisions, missing `id`s, etc.

If we drop `id` from this, it keeps the API the same and we don't have to write our own opinionated collision handling.

Thoughts?

**Comment by BrianSipple** [comment]
Just as a heads up, I have a [branch where I've been getting started on this](https://github.com/BrianSipple/svgstore/tree/option-for-specifying-copied-svg-attributes), and it also include separating the primary functionality of svg-to-symbol conversion into [its own helper function](https://github.com/BrianSipple/svgstore/blob/option-for-specifying-copied-svg-attributes/src/utils/svg-to-symbol.js), outside of `add` (though it's all still a bit experimental, at this point).

As for handling `ids`, I'm right there with you. I've kept that logic separate and made sure we're still setting `id` according to an explicit argument passed for it.

**Comment by BrianSipple** [comment]
Closing since #7 has been merged.
