### ISSUE TITLE
Allow configurable `style` for root SVG / Default to preventing it from taking up space

### ISSUE THREAD

**Issue by BrianSipple** [svgstore/svgstore#8]
This [SO thread](http://stackoverflow.com/questions/16729590/svg-defs-generates-blank-space) provides the most comprehensive insight I could find on the matter, but a very common desire/need for an SVG containing a list of `defs` is to style it so that it takes up no space in the view (but is [still rendered as part of the DOM](http://stackoverflow.com/questions/16729590/svg-defs-generates-blank-space#comment60196192_16729651)). 

With that in mind, I think it would be nice if we set the `style` attribute of our root `svg` like so:

```
<svg ... style="position: absolute; top: 0; left: 0; width: 0%; height: 0%;">
```

Of course, while we're at it, the value we set should also be overridable if the user _does_ want something special.

**Comment by silverwind** [comment]
Alternatively, you could add a `class` option so it can be targeted through CSS. I currently append the `<svg>` to `<body>` and target it through `body > svg`. Certainly not ideal.

**Comment by silverwind** [comment]
Or even more flexible, you could allow a option like `customSvgAttrs`. For example

``` js
svgstore({
  customSvgAttrs: {
    style: 'display: none',
    class: 'icons'
  }
})
```

would result in

``` xml
<svg style="display: none" class="icons"></svg>
```

**Comment by shannonmoeller** [comment]
A custom attributes property sounds like a good idea and it's trivial to implement. Making it configurable also keeps this as least opinionated as possible.

I think we should start a /docs folder with recipies for known common usage like this as well. I'll start a new issue for that.

**Comment by shannonmoeller** [comment]
Started work on this in the [feature/attrs](/svgstore/svgstore/tree/feature/attrs) branch.
