### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by BrianSipple** [svgstore/svgstore#9]
@shannonmoeller Not to clutter the issues too much, but I haven't been able to take advantage of the changes from merging #7 yet. I think we're due for a bump to 1.1.0.

(Also, I wouldn't mind taking care of this if you didn't mind adding `bsipple` as an npm owner. Up to you 😄.)

**Comment by shannonmoeller** [comment]
Released 1.1.0. Also, added you as an npm owner. Sorry for the delay.
